lib = {
   
    @(p,x) cos(p).*x,... 
    @(p,q) cos(p+q),...  
    @(p,q,x) cos(p+q).*x,...
    @(p,u,v) sin(p).*u.*v,...    
    @(u) sign(u),... 
%      @(p,q,u,v) sin(p+q).*u.*v,... 
%     @(u) (u),...   
%     @(u) tanh(u),...
%     @(u) sign(u).*(u<=-1e-4),...
%     @(u) sign(u).*(u>=1e-4),...

%     @(p,q,r,u,v) sin(p+q+r).*u.*v,...
%     @(p,q,r) cos(p+q+r),...
%     @(u) sign(u).*u.^2,...
  

%   @(p,q) sin(p+q),...
%   @(p) sin(p),...
%   @(p,q,x) sin(2*p+q).*x,...
%   @(p,q,x) sin(p+q).*x,... 

%      @(p,q,u,v) cos(2*p+q).*u.*v,...     %addendum
%      @(p,u,v) cos(p).*u.*v,...
%     @(p,q,u,v)cos(p).*sin(q).*u.*v,...
%     @(p,q,x)cos(p).*sin(q).*x,...
    };

libnames = {  
    @(p,x) ['cos(' p ').*' x],... 
    @(p,q) ['cos(' p '+' q ')'],...    
    @(p,q,x) ['cos(' p '+' q ')*' x],...
    @(p,u,v) ['sin(' p ').*' u '.*' v ],...
    @(u) ['sign(' u ')'],...     
%         @(p,q,u,v) ['sin(' p '+' q ')*' u '*' v],...  
%     @(u) ['(' u  ')'],...  %Viscous Friction
%     @(u) ['tanh(' u ')'],...
%     @(u) ['sign(' u ')*(' u '<=-1e-4)'],... %Coulomb Friction
%     @(u) ['sign(' u ')*(' u '>=1e-4)'],... %Coulomb Friction

%     @(p,q,r,u,v) ['sin(' p '+' q '+ ' r ')*' u '*' v],... 
%     @(p,q,r) ['cos(' p '+' q '+' r ')'],...
%     @(u) ['(' u '.^2)*sign(' u ')'],...
%       @(u)  ['(' u ')'],...
%       @(u) ['tanh(' u ')'],...
%     @(p,q) ['sin(' p '+' q ')'],... 
    %@(p) ['sin(' p ')'],...
%     @(p,q,u,v) ['cos(2*' p '+' q ').*' u '.*' v],...
%     @(p,u,v) ['cos(' p ').*' u '.*' v],...
%     @(p,q,x) ['sin(' p '+' q ')*' x],...
%     @(p,q,u,v) ['cos(' p '+' q ')*' u '*' v],...
%     @(p,q,x) ['sin(2*' p '+' q ').*' x ],...
%     @(p,q,u,v) ['cos(' p ').*sin(' q ').*' u '.*' v],...
%     @(p,q,x) ['cos(' p ').*sin(' q ').*' x ],...
};